/**
 * WeldUI Theme Generator — Core logic
 * Handles color scale generation, WCAG contrast checking, and CSS output.
 */

export interface ThemeOptions {
  themeName: string;
  packageName: string;
  displayName: string;
  primaryHex: string;
  surfaceHex: string;
  modes: 'light' | 'dark' | 'both';
  outputDir: string;
}

export interface ContrastIssue {
  pair: string;
  fg: string;
  bg: string;
  ratio: number;
}

// ── Color utilities ──────────────────────────────────────────────────────────

export function hexToRgb(hex: string): [number, number, number] {
  const clean = hex.replace('#', '');
  return [
    parseInt(clean.slice(0, 2), 16),
    parseInt(clean.slice(2, 4), 16),
    parseInt(clean.slice(4, 6), 16),
  ];
}

export function hexToHsl(hex: string): [number, number, number] {
  const [r, g, b] = hexToRgb(hex).map((c) => c / 255) as [number, number, number];
  const max = Math.max(r, g, b);
  const min = Math.min(r, g, b);
  const l = (max + min) / 2;
  let h = 0;
  let s = 0;

  if (max !== min) {
    const d = max - min;
    s = l > 0.5 ? d / (2 - max - min) : d / (max + min);
    switch (max) {
      case r: h = ((g - b) / d + (g < b ? 6 : 0)) / 6; break;
      case g: h = ((b - r) / d + 2) / 6; break;
      case b: h = ((r - g) / d + 4) / 6; break;
    }
  }
  return [Math.round(h * 360), Math.round(s * 100), Math.round(l * 100)];
}

export function hslToHex(h: number, s: number, l: number): string {
  const sl = s / 100;
  const ll = l / 100;
  const c = (1 - Math.abs(2 * ll - 1)) * sl;
  const x = c * (1 - Math.abs(((h / 60) % 2) - 1));
  const m = ll - c / 2;
  let r = 0, g = 0, b = 0;

  if (h < 60)       { r = c; g = x; b = 0; }
  else if (h < 120) { r = x; g = c; b = 0; }
  else if (h < 180) { r = 0; g = c; b = x; }
  else if (h < 240) { r = 0; g = x; b = c; }
  else if (h < 300) { r = x; g = 0; b = c; }
  else              { r = c; g = 0; b = x; }

  const toHex = (v: number) =>
    Math.max(0, Math.min(255, Math.round((v + m) * 255))).toString(16).padStart(2, '0');

  return `#${toHex(r)}${toHex(g)}${toHex(b)}`;
}

// ── Color scale generation ────────────────────────────────────────────────────

/**
 * Lightness targets for each stop (600 = the input primary).
 * Saturation is tapered at extremes.
 */
const SCALE_STOPS: Array<[number, number, number]> = [
  //  stop, lightness, saturation-factor
  [50,  97, 0.25],
  [100, 93, 0.35],
  [200, 86, 0.50],
  [300, 77, 0.70],
  [400, 66, 0.85],
  [500, 56, 0.95],
  [600, 47, 1.00],  // primary maps here
  [700, 38, 0.95],
  [800, 28, 0.85],
  [900, 19, 0.75],
];

export function generateColorScale(primaryHex: string): Map<number, string> {
  const [h, s] = hexToHsl(primaryHex);
  const scale = new Map<number, string>();

  for (const [stop, lightness, sFactor] of SCALE_STOPS) {
    const adjustedS = Math.min(100, Math.round(s * sFactor));
    scale.set(stop, hslToHex(h, adjustedS, lightness));
  }
  return scale;
}

// ── WCAG contrast ─────────────────────────────────────────────────────────────

function relativeLuminance(r: number, g: number, b: number): number {
  return [r, g, b]
    .map((c) => {
      const srgb = c / 255;
      return srgb <= 0.03928 ? srgb / 12.92 : Math.pow((srgb + 0.055) / 1.055, 2.4);
    })
    .reduce((acc, val, i) => acc + val * [0.2126, 0.7152, 0.0722][i], 0);
}

export function contrastRatio(hex1: string, hex2: string): number {
  const l1 = relativeLuminance(...hexToRgb(hex1));
  const l2 = relativeLuminance(...hexToRgb(hex2));
  const lighter = Math.max(l1, l2);
  const darker = Math.min(l1, l2);
  return (lighter + 0.05) / (darker + 0.05);
}

export function checkContrastPairs(
  pairs: Array<{ label: string; fg: string; bg: string }>,
): ContrastIssue[] {
  const issues: ContrastIssue[] = [];
  for (const { label, fg, bg } of pairs) {
    const ratio = contrastRatio(fg, bg);
    if (ratio < 4.5) {
      issues.push({ pair: label, fg, bg, ratio });
    }
  }
  return issues;
}

// ── CSS generation ────────────────────────────────────────────────────────────

export function generateLightCSS(opts: ThemeOptions, scale: Map<number, string>): string {
  const p = (stop: number) => scale.get(stop)!;
  const textOnPrimary = contrastRatio(p(600), '#ffffff') >= 4.5 ? '#ffffff' : '#111827';

  return `/* ${opts.displayName} — Light Theme
 * Generated by create-weldui-theme
 * https://weldui.dev
 */

[data-theme="${opts.themeName}"],
[data-theme="${opts.themeName}-light"] {
  /* ── Brand ── */
  --wu-color-primary:         ${p(600)};
  --wu-color-primary-hover:   ${p(700)};
  --wu-color-primary-subtle:  ${p(50)};
  --wu-color-primary-fg:      ${textOnPrimary};

  /* ── Surface ── */
  --wu-color-background:      ${opts.surfaceHex};
  --wu-color-surface:         ${p(50)};
  --wu-color-surface-raised:  #ffffff;
  --wu-color-surface-overlay: #ffffff;

  /* ── Text ── */
  --wu-color-text:            ${p(900)};
  --wu-color-text-secondary:  ${p(700)};
  --wu-color-text-disabled:   ${p(300)};
  --wu-color-text-inverse:    #ffffff;

  /* ── Border ── */
  --wu-color-border:          ${p(200)};
  --wu-color-border-strong:   ${p(300)};
  --wu-color-border-focus:    ${p(500)};

  /* ── Focus ring ── */
  --wu-focus-ring: 0 0 0 3px ${p(200)};
}
`;
}

export function generateDarkCSS(opts: ThemeOptions, scale: Map<number, string>): string {
  const p = (stop: number) => scale.get(stop)!;
  const textOnPrimary = contrastRatio(p(400), '#111827') >= 4.5 ? '#111827' : '#ffffff';

  return `/* ${opts.displayName} — Dark Theme
 * Generated by create-weldui-theme
 * https://weldui.dev
 */

[data-theme="${opts.themeName}-dark"] {
  /* ── Brand ── */
  --wu-color-primary:         ${p(400)};
  --wu-color-primary-hover:   ${p(300)};
  --wu-color-primary-subtle:  color-mix(in srgb, ${p(500)} 15%, transparent);
  --wu-color-primary-fg:      ${textOnPrimary};

  /* ── Surface ── */
  --wu-color-background:      #090b0f;
  --wu-color-surface:         ${p(900)};
  --wu-color-surface-raised:  ${p(800)};
  --wu-color-surface-overlay: ${p(800)};

  /* ── Text ── */
  --wu-color-text:            ${p(50)};
  --wu-color-text-secondary:  ${p(200)};
  --wu-color-text-disabled:   ${p(700)};
  --wu-color-text-inverse:    ${p(900)};

  /* ── Border ── */
  --wu-color-border:          ${p(800)};
  --wu-color-border-strong:   ${p(700)};
  --wu-color-border-focus:    ${p(400)};

  /* ── Focus ring ── */
  --wu-focus-ring: 0 0 0 3px color-mix(in srgb, ${p(400)} 30%, transparent);
}
`;
}

export function generatePackageJSON(opts: ThemeOptions): string {
  return JSON.stringify(
    {
      name: opts.packageName,
      version: '1.0.0',
      description: `${opts.displayName} theme for WeldUI`,
      files: [
        'light.css',
        ...(opts.modes === 'both' || opts.modes === 'dark' ? ['dark.css'] : []),
        'README.md',
        'preview.html',
      ],
      keywords: ['weldui', 'theme', 'css', 'design-tokens'],
      peerDependencies: {
        '@weldui/core': '>=0.1.0',
      },
      license: 'MIT',
    },
    null,
    2,
  );
}

export function generateReadme(opts: ThemeOptions, scale: Map<number, string>): string {
  const hasLight = opts.modes === 'light' || opts.modes === 'both';
  const hasDark = opts.modes === 'dark' || opts.modes === 'both';
  const themeAttr = opts.modes === 'dark' ? `${opts.themeName}-dark` : opts.themeName;

  return `# ${opts.displayName} Theme for WeldUI

A custom theme for [WeldUI](https://weldui.dev) component library.

**Primary color:** \`${opts.primaryHex}\`  
**Color scale:** ${[50, 100, 200, 300, 400, 500, 600, 700, 800, 900].map((s) => `\`${scale.get(s)}\``).join(', ')}

## Installation

\`\`\`bash
npm install ${opts.packageName}
\`\`\`

## Usage

Import the theme CSS **after** \`@weldui/core\` tokens:

\`\`\`html
<!-- In your HTML -->
<link rel="stylesheet" href="node_modules/@weldui/core/dist/tokens/base.css" />
<link rel="stylesheet" href="node_modules/@weldui/core/dist/tokens/semantic.css" />
${hasLight ? `<link rel="stylesheet" href="node_modules/${opts.packageName}/light.css" />` : ''}
${hasDark ? `<link rel="stylesheet" href="node_modules/${opts.packageName}/dark.css" />` : ''}
\`\`\`

Apply the theme using the \`data-theme\` attribute:

\`\`\`html
<!-- Light mode -->
<body data-theme="${themeAttr}">

${hasDark ? `<!-- Dark mode -->\n<body data-theme="${opts.themeName}-dark">` : ''}
\`\`\`

## Customisation

Override any token by redefining it after the theme import:

\`\`\`css
[data-theme="${themeAttr}"] {
  --wu-color-primary: #your-brand-color;
  --wu-radius-md: 8px; /* rounder corners */
}
\`\`\`

## Generated with

\`\`\`bash
npx create-weldui-theme
\`\`\`
`;
}

export function generatePreviewHTML(opts: ThemeOptions, scale: Map<number, string>): string {
  const hasLight = opts.modes === 'light' || opts.modes === 'both';
  const hasDark = opts.modes === 'dark' || opts.modes === 'both';
  const p = (stop: number) => scale.get(stop)!;

  const colorSwatches = [50, 100, 200, 300, 400, 500, 600, 700, 800, 900]
    .map(
      (stop) =>
        `<div style="display:flex;align-items:center;gap:8px;margin:2px 0">
          <div style="width:32px;height:32px;border-radius:6px;background:${p(stop)};border:1px solid rgba(0,0,0,.1)"></div>
          <code style="font-size:12px">${stop} — ${p(stop)}</code>
        </div>`,
    )
    .join('\n      ');

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>${opts.displayName} Theme Preview — WeldUI</title>
  <script type="module" src="https://cdn.jsdelivr.net/npm/@weldui/core@latest/dist/index.js"></script>
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@weldui/core@latest/dist/tokens/base.css" />
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@weldui/core@latest/dist/tokens/semantic.css" />
  ${hasLight ? '<link rel="stylesheet" href="./light.css" />' : ''}
  ${hasDark ? '<link rel="stylesheet" href="./dark.css" />' : ''}
  <style>
    body { margin: 0; font-family: system-ui, sans-serif; }
    .theme-panel { padding: 32px; min-height: 100vh; }
    .theme-panel h1 { font-size: 1.5rem; font-weight: 700; margin: 0 0 4px; }
    .theme-panel p { margin: 0 0 24px; font-size: 0.875rem; opacity: 0.7; }
    .section { margin-bottom: 32px; }
    .section h2 { font-size: 0.75rem; font-weight: 600; text-transform: uppercase;
                  letter-spacing: 0.08em; opacity: 0.5; margin: 0 0 12px; }
    .row { display: flex; flex-wrap: wrap; gap: 10px; align-items: center; }
    .controls { position: fixed; top: 16px; right: 16px; display: flex; gap: 8px; }
    .controls button { padding: 6px 14px; border-radius: 6px; border: 1px solid #ccc;
                       background: white; cursor: pointer; font-size: 13px; }
  </style>
</head>
<body>
  ${hasLight ? `<div class="theme-panel" data-theme="${opts.themeName}" id="light-panel"
    style="background:var(--wu-color-background);color:var(--wu-color-text)">
    <h1>${opts.displayName}</h1>
    <p>Light theme — WeldUI component preview</p>

    <div class="section">
      <h2>Buttons</h2>
      <div class="row">
        <wu-button variant="primary">Primary</wu-button>
        <wu-button variant="secondary">Secondary</wu-button>
        <wu-button variant="ghost">Ghost</wu-button>
        <wu-button variant="danger">Danger</wu-button>
        <wu-button disabled>Disabled</wu-button>
        <wu-button loading>Loading</wu-button>
      </div>
    </div>

    <div class="section">
      <h2>Button Sizes</h2>
      <div class="row">
        <wu-button size="sm">Small</wu-button>
        <wu-button size="md">Medium</wu-button>
        <wu-button size="lg">Large</wu-button>
      </div>
    </div>

    <div class="section">
      <h2>Badges</h2>
      <div class="row">
        <wu-badge variant="default">Default</wu-badge>
        <wu-badge variant="primary">Primary</wu-badge>
        <wu-badge variant="success">Success</wu-badge>
        <wu-badge variant="warning">Warning</wu-badge>
        <wu-badge variant="danger">Danger</wu-badge>
        <wu-badge variant="outline">Outline</wu-badge>
      </div>
    </div>

    <div class="section">
      <h2>Avatars</h2>
      <div class="row">
        <wu-avatar size="sm" initials="SM"></wu-avatar>
        <wu-avatar size="md" initials="MD"></wu-avatar>
        <wu-avatar size="lg" initials="LG"></wu-avatar>
        <wu-avatar size="xl" initials="XL"></wu-avatar>
      </div>
    </div>

    <div class="section">
      <h2>Form Inputs</h2>
      <div style="display:flex;flex-direction:column;gap:12px;max-width:360px">
        <wu-input label="Email" type="email" placeholder="you@example.com"></wu-input>
        <wu-select label="Plan" placeholder="Choose a plan">
          <option value="starter">Starter</option>
          <option value="pro">Pro</option>
          <option value="enterprise">Enterprise</option>
        </wu-select>
        <wu-textarea label="Notes" rows="3" placeholder="Write something..."></wu-textarea>
        <wu-checkbox>I agree to the terms</wu-checkbox>
        <wu-toggle>Enable notifications</wu-toggle>
      </div>
    </div>

    <div class="section">
      <h2>Color Scale</h2>
      ${colorSwatches}
    </div>
  </div>` : ''}

  ${hasDark ? `<div class="theme-panel" data-theme="${opts.themeName}-dark"
    style="background:var(--wu-color-background);color:var(--wu-color-text)">
    <h1>${opts.displayName}</h1>
    <p>Dark theme — WeldUI component preview</p>

    <div class="section">
      <h2>Buttons</h2>
      <div class="row">
        <wu-button variant="primary">Primary</wu-button>
        <wu-button variant="secondary">Secondary</wu-button>
        <wu-button variant="ghost">Ghost</wu-button>
        <wu-button variant="danger">Danger</wu-button>
        <wu-button disabled>Disabled</wu-button>
        <wu-button loading>Loading</wu-button>
      </div>
    </div>

    <div class="section">
      <h2>Badges</h2>
      <div class="row">
        <wu-badge variant="default">Default</wu-badge>
        <wu-badge variant="primary">Primary</wu-badge>
        <wu-badge variant="success">Success</wu-badge>
        <wu-badge variant="warning">Warning</wu-badge>
        <wu-badge variant="danger">Danger</wu-badge>
        <wu-badge variant="outline">Outline</wu-badge>
      </div>
    </div>

    <div class="section">
      <h2>Avatars</h2>
      <div class="row">
        <wu-avatar size="sm" initials="SM"></wu-avatar>
        <wu-avatar size="md" initials="MD"></wu-avatar>
        <wu-avatar size="lg" initials="LG"></wu-avatar>
        <wu-avatar size="xl" initials="XL"></wu-avatar>
      </div>
    </div>

    <div class="section">
      <h2>Form Inputs</h2>
      <div style="display:flex;flex-direction:column;gap:12px;max-width:360px">
        <wu-input label="Email" type="email" placeholder="you@example.com"></wu-input>
        <wu-checkbox>I agree to the terms</wu-checkbox>
        <wu-toggle>Enable notifications</wu-toggle>
      </div>
    </div>
  </div>` : ''}
</body>
</html>
`;
}
